function handles = WeatherStationGUI(stWeather)
% function to do something usefull (fill out)
% Usage [out_param] = weatherStationModel(in_param)
% Input Parameter:
%	 in_param: 		 Explain the parameter, default values, and units
% Output Parameter:
%	 out_param: 	 Explain the parameter, default values, and units
%------------------------------------------------------------------------ 
% Example: Provide example here if applicable (one or two lines) 

% Author: S.Volke (c) IHA @ Jade Hochschule applied licence see EOF 
% Version History:
% Ver. 0.01 initial create (empty) 09-Apr-2014  Initials (eg. JB)

%------------Your function implementation here--------------------------- 


%stWeather = weatherStationModel('Oldenburg');

handles.h = figure('Units','normalized',...
    'Position',[0.3 0.3 0.6 0.6],...
    'Name','Wetterstation',...
    'Color','white',...
    'NumberTitle','off',...
    'Resize','off',...
    'MenuBar','none',...
    'Toolbar','none');

handles.h_header = uipanel('Parent',handles.h,...
    'Units','normalized',...
    'Position',[0.0 0.8 1.0 0.2],...
    'BackgroundColor','white',...
    'BorderType','none');

handles.h_CityName = uicontrol('Parent',handles.h_header,...
    'Units','normalized',...
    'Position',[0.02 0.3 0.4 0.5],...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',20,...
    'String','--');

for ii = 1:5
    % day Panel
   handles.h_dayPanel(ii) = uipanel('Parent',handles.h,...
       'Units','normalized',...
       'Position',[(ii-1)*(1/5) 0.1 1/5 0.7],...
       'BackgroundColor','white',...
       'BorderType','line');

    % Date Label
    handles.h_dayDate(ii) = uicontrol('Parent',handles.h_dayPanel(ii),...
    'Units','normalized',...
    'Position',[0 0.9 1 0.08],...
    'BackgroundColor','white',...
    'HorizontalAlignment','center',...
    'Style','text',...
    'ForegroundColor',[.252 .252 .252],...
    'FontSize',16,...
    'String','');

    % Date name Panel
    handles.h_dayDateName(ii) = uicontrol('Parent',handles.h_dayPanel(ii),...
    'Units','normalized',...
    'Position',[0 0.83 1 0.1],...
    'BackgroundColor','white',...
    'HorizontalAlignment','center',...
    'Style','text',...
    'FontSize',18,...
    'String','');

    % Day Temperature pic
    handles.h_dayPic(ii) = axes('Parent',handles.h_dayPanel(ii),...
            'Units','normalized',...
            'Position',[0.03 0.65 0.3 0.3]);
    axis off;

    imshow('800d.jpg','InitialMagnification','fit','Parent',handles.h_dayPic(ii));
    
    % Night temperature pic
    handles.h_nightPic(ii) = axes('Parent',handles.h_dayPanel(ii),...
            'Units','normalized',...
            'Position',[0.03 0.55 0.3 0.3]);
    axis off;

    imshow('800n.jpg','InitialMagnification','fit','Parent',handles.h_nightPic(ii));
    
    % Day temperature
    handles.h_dayTemp(ii) = uicontrol('Parent',handles.h_dayPanel(ii),...
        'Units','normalized',...
        'Position',[0.3 0.75 0.45 0.08],...
        'Style','text',...
        'FontSize',17,...
        'BackgroundColor','white',...
        'String','--',...
        'HorizontalAlignment','right');
    
    % night temperature
    handles.h_nightTemp(ii) = uicontrol('Parent',handles.h_dayPanel(ii),...
        'Units','normalized',...
        'Position',[0.3 0.65 0.45 0.08],...
        'Style','text',...
        'FontSize',17,...
        'BackgroundColor','white',...
        'String','--',...
        'HorizontalAlignment','right');
    
    % cloud picture
    handles.h_CloudsPic(ii) = axes('Parent',handles.h_dayPanel(ii),...
            'Units','normalized',...
            'Position',[0.00 0.4 1 0.25]);
    axis off;

    %imagname = [stWeather.getCloudsNameForDay(ii),'d.jpg'];
    %imshow(imagname,'InitialMagnification','fit','Parent',handles.h_CloudsPic(ii));
    
    % cloud description
    handles.h_CloudName(ii) = uicontrol('Parent',handles.h_dayPanel(ii),...
        'Units','normalized',...
        'Position',[0 0.3 1 0.1],...
        'Style','text',...
        'FontSize',15,...
        'BackgroundColor','white',...
        'String','--',...
        'HorizontalAlignment','center');
    
    % wind picture
    handles.h_WindPic(ii) = axes('Parent',handles.h_dayPanel(ii),...
            'Units','normalized',...
            'Position',[0.13 0.15 0.18 0.18]);
    axis off;

    imshow('wind.jpg','InitialMagnification','fit','Parent',handles.h_WindPic(ii));
    
    % wind data
    handles.h_WindData(ii) = uicontrol('Parent',handles.h_dayPanel(ii),...
        'Units','normalized',...
        'Position',[0.22 0.2 0.74 0.06],...
        'Style','text',...
        'FontSize',14,...
        'BackgroundColor','white',...
        'String','--',...
        'HorizontalAlignment','center');

    % humidity pic
    handles.h_HumidityPic(ii) = axes('Parent',handles.h_dayPanel(ii),...
            'Units','normalized',...
            'Position',[0.08 0.05 0.18 0.18]);
    axis off;

    imshow('humidity.jpg','InitialMagnification','fit','Parent',handles.h_HumidityPic(ii));
    
    % humidity Data
    handles.h_HumidityData(ii) = uicontrol('Parent',handles.h_dayPanel(ii),...
        'Units','normalized',...
        'Position',[0.26 0.1 0.54 0.06],...
        'Style','text',...
        'FontSize',14,...
        'BackgroundColor','white',...
        'String','--',...
        'HorizontalAlignment','center'); 
    
    % pressure pic
    handles.h_PressurePic(ii) = axes('Parent',handles.h_dayPanel(ii),...
            'Units','normalized',...
            'Position',[0.1 -0.04 0.16 0.16]);
    axis off;

    imshow('pressure.jpg','InitialMagnification','fit','Parent',handles.h_PressurePic(ii));
    
    % pressure Data
    handles.h_PressureData(ii) = uicontrol('Parent',handles.h_dayPanel(ii),...
        'Units','normalized',...
        'Position',[0.26 0.0 0.54 0.06],...
        'Style','text',...
        'FontSize',14,...
        'BackgroundColor','white',...
        'String','--',...
        'HorizontalAlignment','center'); 
    
    
end
% update Button
uicontrol('Parent',handles.h_header,...
    'Units','normalized',...
    'Position',[0.5 0.5 0.2 0.3],...
    'Style','pushbutton',...
    'Callback','updateWeather(handles,stWeather,1)',...
    'String','Aktualisieren');

% change City Button
uicontrol('Parent',handles.h_header,...
    'Units','normalized',...
    'Position',[0.02 0.3 0.1 0.2],...
    'Style','pushbutton',...
    'Callback','changeCity(handles,stWeather)',...
    'String','Ort ändern');




%--------------------Licence ---------------------------------------------
% Copyright (c) <2014> S.Volke
% Institute for Hearing Technology and Audiology
% Jade University of Applied Sciences 
% Permission is hereby granted, free of charge, to any person obtaining 
% a copy of this software and associated documentation files 
% (the "Software"), to deal in the Software without restriction, including 
% without limitation the rights to use, copy, modify, merge, publish, 
% distribute, sublicense, and/or sell copies of the Software, and to
% permit persons to whom the Software is furnished to do so, subject
% to the following conditions:
% The above copyright notice and this permission notice shall be included 
% in all copies or substantial portions of the Software.
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
% EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
% OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
% IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
% CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
% TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
% SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.