function handles = WeatherStationGUI(stWeather)
% function to generate GUI for weater station
% this file is part of weather Station (see README.md)
% to start weather station run WS_START.m
% Usage handles = WeatherStationGUI()
%
% Input Parameters:
%    stWeater:   actual weater data struct
% Output Parameter:
%	 handles: 	 handles to all elements in figure
%------------------------------------------------------------------------ 

% Author: S.Volke (c) IHA @ Jade Hochschule applied licence see EOF 

%------------Your function implementation here--------------------------- 

% initialize figure
handles.h = figure('Units','normalized',...
    'Position',[0.3 0.3 0.6 0.6],...
    'Name','Wetterstation',...
    'color','blue',...
    'NumberTitle','off',...
    'Resize','off',...
    'MenuBar','none',...
    'Toolbar','none');

% panel for header information
handles.h_header = uipanel('Parent',handles.h,...
    'Units','normalized',...
    'Position',[0.0 0.8 1.0 0.2],...
    'BackgroundColor','white',...
    'BorderType','none');

% panel for footer
handles.h_footer = uipanel('Parent',handles.h,...
    'Units','normalized',...
    'Position',[0.0 0 1.0 0.1],...
    'BackgroundColor','white',...
    'BorderType','none');

% generate city name
handles.h_CityName = uicontrol('Parent',handles.h_header,...
    'Units','normalized',...
    'Position',[0.02 0.3 0.4 0.5],...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',20,...
    'String','--');

% loop for generating forecast GUI elements for 5 days
for ii = 1:5
    
   % day Panel
   handles.h_dayPanel(ii) = uipanel('Parent',handles.h,...
       'Units','normalized',...
       'Position',[(ii-1)*(1/5) 0.1 1/5 0.7],...
       'BackgroundColor','white',...
       'borderwidth',1,...
       'BorderType','etchedin');
   
%% section for date, day and night temp. %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   handles.h_firstThird(ii) = uipanel('Parent',handles.h_dayPanel(ii),...
       'units','normalized',...
       'backgroundcolor', 'white',...
       'bordertype','none',...
       'position',[0 0.666 1 0.333]);
   
    % Night temperature pic
    handles.h_nightPic(ii) = axes('Parent',handles.h_firstThird(ii),...
            'Units','normalized',...
            'Position',[0 0 0.333 0.25]);
    
    nightTempPic = imread('night.jpg');
    image([0 1],[0 1],nightTempPic);
    axis off;
    axis equal;
    box off;
    whitebg('white');
    
    % night temperature
    handles.h_nightTemp(ii) = uicontrol('Parent',handles.h_firstThird(ii),...
        'Units','normalized',...
        'Position',[0.333 0 0.5 0.25],...
        'Style','text',...
        'FontSize',17,...
        'BackgroundColor','white',...
        'String','--',...
        'HorizontalAlignment','right');
    
    % Day Temperature pic
    handles.h_dayPic(ii) = axes('Parent',handles.h_firstThird(ii),...
            'Units','normalized',...
            'Position',[0 0.25 0.333 0.25]);

    dayTempPic = imread('day.jpg');
    image([0 1],[0 1],dayTempPic);
    axis equal;
    axis off;
    box on;
    whitebg('white');

    % Day temperature
    handles.h_dayTemp(ii) = uicontrol('Parent',handles.h_firstThird(ii),...
        'Units','normalized',...
        'Position',[0.333 0.25 0.5 0.25],...
        'Style','text',...
        'FontSize',17,...
        'BackgroundColor','white',...
        'String','--',...
        'HorizontalAlignment','right');

    % Date Label
    handles.h_dayDate(ii) = uicontrol('Parent',handles.h_firstThird(ii),...
    'Units','normalized',...
    'Position',[0 0.75 1 0.25],...
    'BackgroundColor','white',...
    'HorizontalAlignment','center',...
    'Style','text',...
    'ForegroundColor',[.252 .252 .252],...
    'FontSize',16,...
    'String','');
    
    % Date name Panel
    handles.h_dayDateName(ii) = uicontrol('Parent',handles.h_firstThird(ii),...
    'Units','normalized',...
    'Position',[0 0.6 1 0.25],...
    'BackgroundColor','white',...
    'HorizontalAlignment','center',...
    'Style','text',...
    'FontSize',20,...
    'String','');
        
    
%% second third Panel for cloud icon and cloud text %%%%%%%%%%%%%%%%%%%%%%%    
    handles.h_secondThird(ii) = uipanel('Parent',handles.h_dayPanel(ii),...
       'units','normalized',...
       'position',[0 0.333 1 0.333],...
       'bordertype','none',...
       'backgroundcolor','white');
   
  
    handles.h_CloudsPic(ii) = axes('Parent',handles.h_secondThird(ii),...
            'Units','normalized',...
            'Position',[0 0.25 1 0.75]);
        axis([0 1.45 0 1])
    whitebg('white');
    
    
    % cloud description
    handles.h_CloudName(ii) = uicontrol('Parent',handles.h_secondThird(ii),...
        'Units','normalized',...
        'Position',[0 0 1 0.25],...
        'Style','text',...
        'FontSize',15,...
        'BackgroundColor','white',...
        'String','--',...
        'HorizontalAlignment','center');
   
   
%% section for wind humidity and pressure
   handles.h_thirdThird(ii) = uipanel('Parent',handles.h_dayPanel(ii),...
   'units','normalized',...
   'backgroundcolor','white',...
   'bordertype','none',...
   'position',[0 0 1 0.333]);

    
    % wind picture
    handles.h_WindPic(ii) = axes('Parent',handles.h_thirdThird(ii),...
            'Units','normalized',...
            'Position',[0 0.666 0.25 0.333]);
    
    windPic = imread('wind.jpg');
    image([0 1],[0 1],windPic);
    axis equal;
    axis off;
    box on;
    whitebg('white');
    
    
    % wind data
    handles.h_WindData(ii) = uicontrol('Parent',handles.h_thirdThird(ii),...
        'Units','normalized',...
        'Position',[0.25 0.6 0.75 0.333],...
        'Style','text',...
        'FontSize',14,...
        'BackgroundColor','white',...
        'String','--',...
        'HorizontalAlignment','center');

    % humidity pic
    handles.h_HumidityPic(ii) = axes('Parent',handles.h_thirdThird(ii),...
            'Units','normalized',...
            'Position',[0 0.333 0.25 0.333]);
    humiPic = imread('humidity.jpg');
    image([0 1],[0 1],humiPic);
    axis equal;
    axis off;
    whitebg('white');
    
    % humidity Data
    handles.h_HumidityData(ii) = uicontrol('Parent',handles.h_thirdThird(ii),...
        'Units','normalized',...
        'Position',[0.25 0.266 0.75 0.333],...
        'Style','text',...
        'FontSize',14,...
        'BackgroundColor','white',...
        'String','--',...
        'HorizontalAlignment','center'); 
    
    % pressure pic
    handles.h_PressurePic(ii) = axes('Parent',handles.h_thirdThird(ii),...
            'Units','normalized',...
            'Position',[0 0 0.25 0.333]);
        
    pressPic = imread('pressure.jpg');
    image([0 1],[0 1],pressPic);
    axis equal;
    axis off;
    whitebg('white');
    
    
    % pressure Data
    handles.h_PressureData(ii) = uicontrol('Parent',handles.h_thirdThird(ii),...
        'Units','normalized',...
        'Position',[0.25 0.05 0.75 0.2],...
        'Style','text',...
        'FontSize',14,...
        'BackgroundColor','white',...
        'String','--',...
        'HorizontalAlignment','center'); 
    
    
end




% updatetime Display
handles.h_updateTime = uicontrol('Parent',handles.h_header,...
        'Units','normalized',...
        'Position',[0.8 0.4 0.2 0.3],...
        'Style','text',...
        'FontSize',12,...
        'BackgroundColor','white',...
        'String','--',...
        'HorizontalAlignment','center');
    
% change City Button
uicontrol('Parent',handles.h_header,...
    'Units','normalized',...
    'Position',[0.1 0.1 0.1 0.2],...
    'Style','pushbutton',...
    'Callback',{@changeCity,handles,stWeather},...
    'String','Ort ändern');

% update Button
uicontrol('Parent',handles.h_header,...
    'Units','normalized',...
    'Position',[0.6 0.4 0.2 0.3],...
    'Style','pushbutton',...
    'Callback',{@updateData,handles,stWeather},...
    'String','Daten aktualisieren');

%--------------------Licence ---------------------------------------------
% Copyright (c) <2014> S.Volke
% Institute for Hearing Technology and Audiology
% Jade University of Applied Sciences 
% Permission is hereby granted, free of charge, to any person obtaining 
% a copy of this software and associated documentation files 
% (the "Software"), to deal in the Software without restriction, including 
% without limitation the rights to use, copy, modify, merge, publish, 
% distribute, sublicense, and/or sell copies of the Software, and to
% permit persons to whom the Software is furnished to do so, subject
% to the following conditions:
% The above copyright notice and this permission notice shall be included 
% in all copies or substantial portions of the Software.
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
% EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
% OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
% IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
% CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
% TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
% SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.